routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::prefix('admin')->namespace('Admin')->middleware(['auth', 'admin'])
->group(function(){
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('pengajar', 'pengajarController');
    Route::resource('kategori', 'kategoriController');
    Route::resource('course', 'CourseController');
    // Route::post('/kategori', 'kategoriController@store')->name('kategori');
    Route::post('chapter/create/{id}', 'chapterController@create')->name('chapter-create');
    // lesson
    Route::post('/lesson/create/{id}', 'LessonController@store')->name('create-lesson');
    Route::get('/chapter/{course_id}/lesson/edit/{id}', 'LessonController@edit')->name('lesson-edit');
    Route::put('/chapter/{course_id}/lesson/update/{id}', 'lessonController@update')->name('lesson-update');
    Route::get('/chapter/{course_id}/lesson/delete/{id}', 'lessonController@destroy')->name('lesson-delete');
});

Route::get('/keluar', '\App\Http\Controllers\Auth\LoginController@logout')->name('keluar');
Auth::routes();


// Route::get('/home', 'HomeController@index')->name('home');

app/Models/mentor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class mentor extends Model
{
    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:m:s',
        'updated_at' => 'datetime:Y-m-d H:m:s',
    ];
    protected $fillable = [
        'nama', 'profile', 'email', 'profession'
    ];

    public function course(){
        return $this->hasMany( Course::class, 'mentor_id', 'id' );
    }
}

app/Http/Controllers/Admin/MentorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\mentor;
use Illuminate\Http\Request;

class MentorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $jMentro = mentor::count();
        $mentor = mentor::get()->all();

        return view('pages.admin.mentor');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/mentorController.php
<?php

namespace App\Http\Controllers;

use App\Models\mentor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class mentorController extends Controller
{
    public function index(){
        $data = mentor::get();

        return response()->json([
            'status' => 'success',
            'data' => $data
        ], 200);
    }
    public function creat(Request $request){
        $rules = [
            'nama' => 'required|string',
            'profile' => 'required|url',
            'profession' => 'required|string',
            'email' => 'required|email'
        ];
        $data = $request->all();

        $validator = Validator::make($data, $rules);
        if($validator->fails()){
            return response()->json([
                'status' => 'error',
                'message' => $validator->errors(),
            ], 400);
        }
        $mentor = mentor::create($data);
        return response()->json([
            'status' => 'success',
            'message' => 'data berhasil di simpan',
            'data' => $mentor,
        ], 200);
    }

    public function update(Request $request, $id){
        $rules = [
            'nama' => 'string',
            'profile' => 'url',
            'profession' => 'string',
            'email' => 'email'
        ];
        $data = $request->all();
         $validator = Validator::make($data, $rules);
        if($validator->fails()){
            return response()->json([
                'status' => 'error',
                'message' => $validator->errors(),
            ], 400);
        }
        $mentor = mentor::find($id);
        if(!$mentor){
            return response()->json([
                'status' => 'error',
                'message' => 'mentor not found'
            ], 404);
        }

        $mentor->fill($data);

        $mentor->save();
        return response()->json([
            'status' => 'success',
            'message' => 'data berhasil di ubah',
            'data' => $mentor,
        ], 200);

    }

    public function show($id){
        $data = mentor::whereId($id)->first();
        if(!$data){
            return response()->json([
                'status' => 'error',
                'message' => 'data not found',
            ], 404);
        }

        return response()->json([
            'status' => 'success',
            'message' => 'Mentor Detail',
            'data' => $data
        ]);
    }
    public function destroy($id){
        $mentor = mentor::find($id);

        if($mentor){
            $mentor->delete();
            return response()->json([
                'status' => 'success',
                'message' => 'data berhasil di hapus'
            ], 200);
        }
        return response()->json([
            'status' => 'error',
            'message' => 'data mentor tidak di temukan'
        ], 404);
    }
    
}

resources/views/pages/admin/mentor/create.blade.php
@extends('layouts.admin')

@section('title')
Tambah Mentor
@endsection

@section('content')
    <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="card shadow">
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <h5 class="card-title">Input Data Mentor</h5>
                            <form action="{{ route('pengajar.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                         <div class="form-group">
                                            <label for="exampleFormControlFile1">Masukan Photo</label>
                                            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="profile">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Nama</label>
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="nama" placeholder="Masukan nama" value="{{ old('nama') }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Email</label>
                                        <div class="form-group">
                                            <input type="email" class="form-control" placeholder="Masukan Email" name="email" value="{{ old('email') }}">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <label for="">Profession</label>
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Masukan Profession" name="profession" value="{{ old('nama') }}">
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/mentor/detail.blade.php
@extends('layouts.admin')

@section('title')
Detail mentor
@endsection
@section('content')
<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center">
                    <img src="{{ Storage::url($item->profile) }}" alt="" class="img-fluid rounded-circle img-profile img-thumbnail">
                </div>
                <div class="col-12 text-center">
                    <h2 class="title-name">{{ $item->nama }}</h2>
                    <p>{{ $item->profession }}</p>
                </div>
                <div class="col-12">
                    
                </div>
                @foreach ($item->course as $course)
                    <div class="col-md-4">
                    <div class="card" >
                        <img class="card-img-top" src="..." alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{ $course->nama }}</h5>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
    </div>
</div>
    
@endsection
@push('addon-style')
    <link href="{{ url('css/style.css') }}" rel="stylesheet">
@endpush

resources/views/pages/admin/mentor/edite.blade.php
@extends('layouts.admin')

@section('title')
Tambah Mentor
@endsection

@section('content')
    <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="card shadow">
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <h5 class="card-title">Edit Data Mentor</h5>
                            <form action="{{ route('pengajar.update', $item->id) }}" method="post" enctype="multipart/form-data">
                                @method('PUT')
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                         <div class="form-group">
                                            <label for="exampleFormControlFile1">Masukan Photo</label>
                                            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="profile">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Nama</label>
                                        <div class="form-group">
                                            <input type="text" class="form-control" name="nama" placeholder="Masukan nama" value="{{ $item->nama }}">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="">Email</label>
                                        <div class="form-group">
                                            <input type="email" class="form-control" placeholder="Masukan Email" name="email" value="{{ $item->email }}">
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <label for="">Profession</label>
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Masukan Profession" name="profession" value="{{ $item->profession }}">
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/mentor/index.blade.php
@extends('layouts.admin')

@section('title')
Mentor Page
@endsection

@section('content')
    <!-- Begin Page Content -->
                <div class="container-fluid">
                        <div class="row mb-4">
                            <div class="col text-right">
                                <a href="{{ route('pengajar.create') }}" class="btn btn-primary"><i class="fas fa-plus fa-sm text-white"></i> Tambah Mentor</a>
                            </div>
                        </div>
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-primary">Jumlah Data Tables Mentor {{ $jMentor }}</h6>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr class="text-center">
                                            <th>Nama</th>
                                            <th>Profession</th>
                                            <th>Email</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse ($mentor as $m)
                                            <tr>
                                                <td>{{ $m->nama }}</td>
                                                <td>{{ $m->profession }}</td>
                                                <td>{{ $m->email }}</td>
                                                <td class="text-center">
                                                    <a href="{{ route('pengajar.show', $m->id) }}" class="btn btn-primary btn-sm mx-1">
                                                        <i class="fa fa-eye"></i> Detail
                                                    </a>
                                                    <a href="{{ route('pengajar.edit', $m->id) }}" class="btn btn-info btn-sm mx-1">
                                                        <i class="fa fa-pencil-alt"></i> Edit
                                                    </a>
                                                    <form action="{{ route('pengajar.destroy', $m->id) }}" method="post" class="d-inline">
                                                        @csrf
                                                        @method('delete')
                                                        <button class="btn btn-danger btn-sm mx-1" onclick="return confirm('Hapus Data ?')">
                                                            <i class="fa fa-trash"></i> Hapus
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @empty
                                             <td colspan="7" class="text-center">
                                                Data Kosong
                                            </td>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->
@endsection