routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::prefix('admin')->namespace('Admin')->middleware(['auth', 'admin'])
->group(function(){
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('pengajar', 'pengajarController');
    Route::resource('kategori', 'kategoriController');
    Route::resource('course', 'CourseController');
    // Route::post('/kategori', 'kategoriController@store')->name('kategori');
    Route::post('chapter/create/{id}', 'chapterController@create')->name('chapter-create');
    // lesson
    Route::post('/lesson/create/{id}', 'LessonController@store')->name('create-lesson');
    Route::get('/chapter/{course_id}/lesson/edit/{id}', 'LessonController@edit')->name('lesson-edit');
    Route::put('/chapter/{course_id}/lesson/update/{id}', 'lessonController@update')->name('lesson-update');
    Route::get('/chapter/{course_id}/lesson/delete/{id}', 'lessonController@destroy')->name('lesson-delete');
});

Route::get('/keluar', '\App\Http\Controllers\Auth\LoginController@logout')->name('keluar');
Auth::routes();


// Route::get('/home', 'HomeController@index')->name('home');

app/Models/Course.php
<?php

namespace App\Models;

use App\Kategori;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    protected $casts = [
        'created_at' => 'datetime:Y-m-d H:m:s',
        'updated_at' => 'datetime:Y-m-d H:m:s',
    ];

    protected $fillable = [
        'nama', 'sertifikat', 'thumbnail', 'type', 'price', 'level', 'deskripsi', 'mentor_id', 'kategori_id'
    ];
    // protected $primaryKey = 'kategori_id';

    public function mentor(){
        return $this->belongsTo('App\Models\mentor');
    }
    public function kategori(){
        return $this->belongsTo(Kategori::class, 'kategori_id', 'id');
    }
    public function chapters(){
        return $this->hasMany('App\Models\Chapter')->orderBy('id', 'ASC');
    }

    public function images(){
        return $this->hasMany('App\Models\Image_course')->orderBy('id', 'DESC');
    }
}

app/Http/Controllers/Admin/CourseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Kategori;
use App\Models\Course;
use App\Models\Lesson;
use App\Models\mentor;
use App\Models\My_course;
use App\Models\Review;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $kategori = Kategori::get();
        $course = Course::with([
            'kategori', 'mentor'
            ])->get();
        $jCourse = Course::count();
        // dd($course);
        return view('pages.admin.course.index',[
            'kategori' => $kategori,
            'course' => $course,
            'jCourse' => $jCourse
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mentor = mentor::get();
        $kategori = Kategori::get();
        return view('pages.admin.course.create', [
            'mentor' => $mentor,
            'kategori' => $kategori
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required|string',
            'sertifikat' => 'required',
            'thumbnail' => 'required|image',
            'type' => 'required|in:free,premium',
            'level' => 'required|in:all-level,beginer,intermedaite,advance',
            'mentor_id' => 'required|integer',
            'deskripsi' => 'string'
        ]);
        $data = $request->all();
        $data['thumbnail'] = $request->file('thumbnail')->store(
            'assets/image/thumbnail course', 'public'
        );
        // dd($data);
        Course::create($data);
        return redirect()->route('course.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Course::with([
            'chapters.lessons', 'mentor', 'kategori'
            ])->findOrFail($id);
        $review = Review::where('course_id', $id)->get()->toArray();
        $totalStudent = My_course::where('course_id', '=', $id)->count();
        $data['reviews'] = $review;
        $data['total_student'] = $totalStudent;

        // dd($data);
        return view('pages.admin.course.detail', [
            'data' => $data,
            'course_id' => $data['id'],
        ]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Course::findOrFail($id);
        // dd($data->deskripsi);
        $mentor = mentor::get();
        $kategori = Kategori::get();
        return view('pages.admin.course.edite', [
            'item' => $data,
            'deskripsi' => $data->deskripsi,
            'mentor' => $mentor,
            'kategori' => $kategori
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required|string',
            'sertifikat' => 'required',
            'thumbnail' => 'required|image',
            'type' => 'required|in:free,premium',
            'level' => 'required|in:all-level,beginer,intermedaite,advance',
            'mentor_id' => 'required|integer',
            'deskripsi' => 'string'
        ]);
        $course = Course::findOrFail($id);

        $data = $request->all();
        $data['thumbnail'] = $request->file('thumbnail')->store(
            'assets/image/thumbnail course', 'public'
        );

        $course->update($data);

        return redirect()->route('course.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Course::findOrFail($id);

        $data->delete();
        return redirect()->route('course.index');
    }
}


// https://www.youtube.com/watch?v=n_szaZBDvQ4
// https://www.youtube.com/watch?v=RiNete2CSHc

app/Http/Controllers/api/courseController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\mentor;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class courseController extends Controller
{
    public function index(){
        $data = Course::get();

         return response()->json([
            'status' => 'success',
            'data' => $data
        ], 200);
    }
    public function create(Request $request){
        $rules = [
            // 'nama', 'sertifikat', 'thumbnail', 'type', 'price', 'level', 'deskripsi', 'mentor_id'
            'nama' => 'required|string',
            'sertifikat' => 'required|boolean',
            'thumbnail' => 'string|url',
            'type' => 'required|in:free,premium',
            'price' => 'integer',
            'level' => 'required|in:all-level,beginer,intermedaite,advance',
            'mentor_id' => 'required|integer',
            'deskripsi' => 'string'
        ];
        $data = $request->all();

        $validator = Validator::make($data, $rules);
        if($validator->fails()){
            return response()->json([
                'status' => 'error',
                'message' => $validator->errors(),
            ], 400);
        }
        $mentorId = $request->input('mentor_id');
        $mentor = mentor::find($mentorId);
        if(!$mentor){
            return response()->json([
                'status' => 'error',
                'message' => 'id mentor tidak di temukan'
            ], 404);
        }
        $course = Course::create($data);
        return response()->json([
            'status' => 'success',
            'message' => 'Course berhasil di buat',
            'data' => $course,
        ], 200);
    }

    public function update(Request $request, $id){
        $rules = [
            'nama' => 'string',
            'sertifikat' => 'boolean',
            'thumbnail' => 'string|url',
            'type' => 'in:free,premium',
            'price' => 'integer',
            'level' => 'in:all-level,beginer,intermedaite,advance',
            'mentor_id' => 'integer',
            'deskripsi' => 'string'
        ];
        $data = $request->all();
         $validator = Validator::make($data, $rules);
        if($validator->fails()){
            return response()->json([
                'status' => 'error',
                'message' => $validator->errors(),
            ], 400);
        }
        $course = Course::find($id);
        if(!$course){
            return response()->json([
                'status' => 'error',
                'message' => 'course not found'
            ], 404);
        }
        // cari mentor berdasarkan id
        $mentorId = $request->input('mentor_id');
        if($mentorId){
            $mentor = mentor::find($mentorId);
            if(!$mentor){
                return response()->json([
                    'status' => 'error',
                    'message' => 'id mentor tidak di temukan'
                ], 404);
            }
        }
        $course->fill($data);

        $course->save();
        return response()->json([
            'status' => 'success',
            'message' => 'data berhasil di ubah',
            'data' => $course,
        ], 200);
    }

    public function show($id){
        $data = Course::whereId($id)->first();
        if(!$data){
            return response()->json([
                'status' => 'error',
                'message' => 'id Course tidak di temukan',
            ], 404);
        }

        return response()->json([
            'status' => 'success',
            'message' => 'Course Detail',
            'data' => $data
        ]);
    }
     public function destroy($id){
        $data = Course::find($id);

        if($data){
            $data->delete();
            return response()->json([
                'status' => 'success',
                'message' => 'data berhasil di hapus'
            ], 200);
        }
        return response()->json([
            'status' => 'error',
            'message' => 'id course tidak di temukan'
        ], 404);
    }
}

resources/views/pages/admin/course/create.blade.php
@extends('layouts.admin')

@section('title')
Tambah Course
@endsection

@section('content')
    <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="card shadow">
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <h5 class="card-title">Input Data Course</h5>
                            <form action="{{ route('course.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                         <div class="form-group">
                                            <label for="exampleFormControlFile1">Masukan thumbnail</label>
                                            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="thumbnail">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">Nama Kelas</label>
                                        <div class="form-group"><input type="text" class="form-control" name="nama" value="{{ old('nama') }}"></div>
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">Type</label>
                                        <select class="form-control" name="type">
                                            <option value="free">Free</option>
                                            <option value="premium">Premium</option>
                                        </select>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="">Bersertifikat</label>
                                        <select class="form-control" name="sertifikat">
                                            <option value="0" @if (old('active') == 0) selected @endif>Tidak</option>
                                            <option value="1" @if (old('active') == 1) selected @endif>Iya</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">Kategori</label>
                                        <select name="kategori_id" class="form-control">
                                            @foreach ($kategori as $k)
                                                <option value="{{ $k->id }}">{{ $k->nama }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="">Price</label>
                                        <div class="form-group"><input type="number" value="0" class="form-control" name="price"></div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="">Level</label>
                                        <select class="form-control" name="level">
                                            <option value="all-level">All Level</option>
                                            <option value="beginer">Baginer</option>
                                            <option value="intermediate">Intermediate</option>
                                            <option value="advance">Advance</option>
                                        </select>
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">Mentor</label>
                                        <select class="form-control" name="mentor_id">
                                            @foreach ($mentor as $item)
                                                <option value="{{ $item->id }}">
                                                    {{ $item->nama }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-10 mb-5">
                                        <label for="exampleFormControlTextarea1">Deskripsi</label>
                                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="deskripsi">{{ old('deskripsi') }}</textarea>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/course/edite.blade.php
@extends('layouts.admin')

@section('title')
Edit Course
@endsection

@section('content')
    <!-- Begin Page Content -->
                <div class="container-fluid">

                    <div class="card shadow">
                        <div class="card-body">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <h5 class="card-title">Edit Data Course</h5>
                            <form action="{{ route('course.update', $item->id) }}" method="post" enctype="multipart/form-data">
                                @method('PUT')
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                         <div class="form-group">
                                            <label for="exampleFormControlFile1">Masukan thumbnail</label>
                                            <input type="file" class="form-control-file" id="exampleFormControlFile1" name="thumbnail">
                                        </div>
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">Nama Kelas</label>
                                        <div class="form-group"><input type="text" class="form-control" name="nama" value="{{ $item->nama}}"></div>
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">Type</label>
                                        <select class="form-control" name="type">
                                            <option value="free">Free</option>
                                            <option value="premium">Premium</option>
                                        </select>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="">Bersertifikat</label>
                                        <select class="form-control" name="sertifikat">
                                            <option value="0" @if (old('active') == 0) selected @endif>Tidak</option>
                                            <option value="1" @if (old('active') == 1) selected @endif>Iya</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <label for="">Kategori</label>
                                        <select name="kategori_id" class="form-control">
                                            @foreach ($kategori as $k)
                                                <option value="{{ $k->id }}">{{ $k->nama }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-md-3">
                                        <label for="">Price</label>
                                        <div class="form-group"><input type="number" value="0" class="form-control" name="price" value="{{ $item->price }}"></div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="">Level</label>
                                        <select class="form-control" name="level">
                                            <option value="all-level">All Level</option>
                                            <option value="beginer">Baginer</option>
                                            <option value="intermediate">Intermediate</option>
                                            <option value="advance">Advance</option>
                                        </select>
                                    </div>
                                    <div class="col-md-5">
                                        <label for="">Mentor</label>
                                        <select class="form-control" name="mentor_id">
                                            @foreach ($mentor as $item)
                                                <option value="{{ $item->id }}">
                                                    {{ $item->nama }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="col-10 mb-5">
                                        <label for="">Deskrips</label>
                                        {{ $item->deskripsi }}
                                        <textarea class="form-control" id="" rows="3" name="deskripsi">{{ $deskripsi }}</textarea>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Tambah</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/course/index.blade.php
@extends('layouts.admin')

@section('title')
Course Page
@endsection

@section('content')
    <!-- Begin Page Content -->
                <div class="container-fluid">
                        <div class="row mb-4">
                            {{-- modal tambah kategori --}}
                            <div class="col">
                                    <!-- Button trigger modal -->
                                <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalCenter">
                                Tambah Kategori
                                </button>
                                <br>
                                @forelse ($kategori as $k)
                                  <button class="btn btn-outline-dark btn-sm mt-3">{{ $k->nama }}</button>
                                @empty
                                    Kategori Kosong
                                @endforelse 
                                <form action="{{ route('kategori.store')}}" method="post" enctype="multipart/form-data">
                                <!-- Modal -->
                                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                    <div class="modal-dialog " role="document">
                                        <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                            
                                             @csrf
                                             <label for="exampleFormControlFile1">Icon</label>
                                                <input type="file" class="form-control-file" id="exampleFormControlFile1" name="image">
                                             <label for="">Nama Kategori</label>
                                             <input type="text" class="form-control" name="nama">
                                            
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                    </form>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
            
                            <div class="col text-right">
                                <a href="{{ route('course.create') }}" class="btn btn-primary"><i class="fas fa-plus fa-sm text-white"></i> Tambah Course</a>
                            </div>
                        </div>
                    <!-- DataTales Example -->
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                                <h6>Table Course</h6>
                        </div>
                        <div class="card-body">
                            <div class="row">
                            @foreach ($course as $c)
                                <div class="col-md-4">
                                    <div class="card">
                                        <img class="card-img-top" src="{{ Storage::url($c->thumbnail) }}" alt="Card image cap">
                                        <div class="card-body">
                                            <h5 class="teks-title-course">{{ $c->nama }}</h5>
                                            <p class="teks-image">{{ $c->type }} 
                                                    <span>{{ $c->level }}</span>
                                             </p>
                                            <hr>
                                               <p>Rp. {{ $c->price }}</p>  
                                                <hr>
                                                <div class="row no-gutters">
                                                    <div class="col-auto ">
                                                        <img src="{{ Storage::url($c->mentor->profile) }}" class="img-fluid rounded-circle img-mentor-course">
                                                    </div>
                                                    <div class="col pl-2">
                                                        <h6 style="margin-bottom: 0px; color: black">{{ $c->mentor->nama }}</h6>
                                                        <p style="margin-top: 0px;">{{ $c->mentor->profession }}</p>
                                                    </div>
                                                    <div class="col-12 text-center">
                                                        <a href="{{ route('course.edit', $c->id) }}" class="btn btn-primary btn-sm mx-1">Edit</a>
                                                        <a href="{{ route('course.show', $c->id) }}" class="btn btn-info btn-sm mx-1">Materi Kelas</a>
                                                       <form action="{{ route('course.destroy', $c->id) }}" method="post" class="d-inline">
                                                            @csrf
                                                            @method('delete')
                                                            <button class="btn btn-outline-danger btn-sm mx-1" onclick="return confirm('Hapus Data ?')"> Hapus
                                                            </button>
                                                        </form>
                                                    </div>
                                                </div>
                                            
                                        </div>
                                    </div>
                                </div>
                                {{-- <div class="card my-2">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-4">
                                                <img src="{{ Storage::url($c->thumbnail) }}" class="img-fluid img-thumbnail-course">
                                            </div>
                                            <div class="col-md-4">
                                                <h5 class="teks-title-course">{{ $c->nama }}</h5>
                                                <p class="teks-image">{{ $c->type }} <span>{{ $c->level }}</span></p> 
                                                <hr>
                                                <span class="course-price">Rp. {{ $c->price }}</span> 
                                                <span class="sertifikat" style="{{ $c->sertifkat ? 'yes' : 'text-decoration: line-through ;' }}">{{ $c->sertifikat ? "sertifikat" : "Sertifikat" }}</span>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div> --}}
                            @endforeach
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->
@endsection
@push('addon-style')
    <link href="{{ url('css/style.css') }}" rel="stylesheet">
@endpush