routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::prefix('admin')->namespace('Admin')->middleware(['auth', 'admin'])
->group(function(){
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('pengajar', 'pengajarController');
    Route::resource('kategori', 'kategoriController');
    Route::resource('course', 'CourseController');
    // Route::post('/kategori', 'kategoriController@store')->name('kategori');
    Route::post('chapter/create/{id}', 'chapterController@create')->name('chapter-create');
    // lesson
    Route::post('/lesson/create/{id}', 'LessonController@store')->name('create-lesson');
    Route::get('/chapter/{course_id}/lesson/edit/{id}', 'LessonController@edit')->name('lesson-edit');
    Route::put('/chapter/{course_id}/lesson/update/{id}', 'lessonController@update')->name('lesson-update');
    Route::get('/chapter/{course_id}/lesson/delete/{id}', 'lessonController@destroy')->name('lesson-delete');
});

Route::get('/keluar', '\App\Http\Controllers\Auth\LoginController@logout')->name('keluar');
Auth::routes();


// Route::get('/home', 'HomeController@index')->name('home');

resources/views/includes/modalCekVideo.blade.php
{{-- Modal Video --}}
                    <div class="modal fade" id="tes{{ $lesson->id }}" tabindex="-1" role="dialog" aria-labelledby="modalSayaLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalSayaLabel">{{ $chapter->nama }}
                                        <br>
                                        <span style="font-weight: normal">{{ $lesson->nama }}</span>
                                    </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <br/>
                                    <div class="embed-responsive embed-responsive-16by9">
                                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ $lesson->video }}" allowfullscreen>
                                        </iframe>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                                    {{-- <button type="button" class="btn btn-primary">Oke</button> --}}
                                </div>
                            </div>
                        </div>
                    </div>

resources/views/includes/sidebar.blade.php
<!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                {{-- <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div> --}}
                <div class="sidebar-brand-text mx-3">Administator</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">
            <!-- Nav Item - Dashboard -->
            <li class="nav-item {{ (request()->is('admin')) ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('dashboard') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item {{ (request()->is('admin/pengajar')) ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('pengajar.index') }}">
                    <i class="fas fa-fw fa-chalkboard-teacher"></i> 
                    <span>Mentor</span>
                </a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item {{ (request()->is('admin/course')) ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('course.index') }}">
                    <i class="far fa-address-card"></i>
                    <span>Course</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('keluar') }}">
                    <i class="fas fa-fw fa-sign-out-alt"></i>
                    <span>Logout</span>
                </a>
            </li>
            <!-- Heading -->
            {{-- <div class="sidebar-heading">
                Interface
            </div> --}}


            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            

        </ul>
        <!-- End of Sidebar -->

resources/views/includes/tambahChapter.blade.php
<form action="{{ route('chapter-create', $course_id)}}" method="post" enctype="multipart/form-data">
                 @csrf
                    <div class="modal fade" id="tambahChapter" tabindex="-1" role="dialog" aria-labelledby="modalSayaLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalSayaLabel">Tambah Chapter
                                    </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <br/>
                                    <div class="form-group">
                                        <label>Course id</label>
                                        <input class="form-control" type="text" placeholder="{{$course_id}}" value="{{$course_id}}" name="course_id" readonly>
                                        <label for="">Judul Materi</label>
                                        <input type="text" class="form-control" name="nama">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

resources/views/includes/tambahVideo.blade.php
<form action="{{ route('create-lesson', $course_id)}}" method="post" enctype="multipart/form-data">
                 @csrf
                    <div class="modal fade" id="tambahLesson{{ $chapter->id }}" tabindex="-1" role="dialog" aria-labelledby="modalSayaLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalSayaLabel">{{ $chapter->nama }}
                                    </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <br/>
                                    <div class="form-group">
                                        <label>Chapter Id</label>
                                        <input class="form-control" type="text" placeholder="{{$chapter->nama}}" value="{{$chapter->id}}" name="chapter_id" readonly>
                                        <label for="">Judul Video Materi</label>
                                        <input type="text" class="form-control" name="nama">
                                        <label for="">Url Youtube Video Materi</label>
                                        <input type="text" class="form-control" name="video">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                </div>
                            </div>
                        </div>
                    </div>
</form>

resources/views/includes/topbar.blade.php
<!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <h6>Ruang Ngelmu Admin</h6>
                    <!-- Topbar Search -->
                    {{-- <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form> --}}

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ Auth::user()->name }}</span>
                                <img class="img-profile rounded-circle"
                                    src="{{ url('backend/img/undraw_profile.svg') }}">
                            </a>
                           
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->